name: Build project

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build solution
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" "opppo_task1/opppo_task1.sln" `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:CL=/utf-8 `
            /p:UsePrecompiledHeader=false `
            /p:LanguageStandard=c++17

