name: Clang-Format

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

jobs:
  format:
    runs-on: windows-latest

    env:
      PAT: ${{ secrets.PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Install LLVM (clang-format)
        shell: pwsh
        run: |
          choco install llvm -y
          refreshenv

      - name: Run clang-format
        shell: pwsh
        run: |
          $clangFormat = "C:\Program Files\LLVM\bin\clang-format.exe"
          Get-ChildItem -Path "." -Recurse -Include "*.cpp","*.h" | ForEach-Object {
            & $clangFormat -i $_.FullName
          }

      - name: Commit and push changes
        shell: pwsh
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git checkout -b clang-format-fix
          git add .
          git commit -m "Apply clang-format" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ env.PAT }}@github.com/Korobkov124/OPPPO.git
          git push origin clang-format-fix --force