name: Format Code

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  clang-format:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup LLVM
        shell: pwsh
        run: choco install llvm -y

      - name: Apply clang-format
        shell: pwsh
        run: |
          $clangFormat = "C:\Program Files\LLVM\bin\clang-format.exe"
          Get-ChildItem -Path "opppo_task1" -Recurse -Include "*.cpp","*.h" | ForEach-Object {
              & $clangFormat -i $_.FullName
          }

      - name: Configure Git
        shell: pwsh
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Commit changes
        shell: pwsh
        run: |
          git add .
          git diff --cached --quiet || git commit -m "Apply clang-format"

      - name: Push changes
        shell: pwsh
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://$env:GH_PAT@github.com/${{ github.repository }}.git
          git push origin HEAD:dev
