name: Static Analysis

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  cppcheck:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cppcheck
        shell: pwsh
        run: choco install cppcheck -y
      
      - name: Run Cppcheck
        shell: pwsh
        run: cppcheck --enable=all --inline-suppr --std=c++17 "opppo_task1" 2> cppcheck_results.txt

