name: Static Analysis

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  cppcheck:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cppcheck via Chocolatey
        shell: pwsh
        run: |
          choco install cppcheck -y
          refreshenv  # чтобы путь к cppcheck обновился

      - name: Run Cppcheck
        shell: pwsh
        run: |
          Write-Host "Running Cppcheck..."
          cppcheck --enable=all --inline-suppr --std=c++17 "opppo_task1" 2> cppcheck_results.txt
          if (Test-Path cppcheck_results.txt) {
            Write-Host "Cppcheck results:"
            Get-Content cppcheck_results.txt
          }
